### ISSUE TITLE
WARNING: tempfile is deprecated; consider using mktemp instead.

### ISSUE THREAD

**Issue by Toilal** [inetum-orleans/docker-devbox-ddb#214]
I have this warning with ddb binary shims on a pipeline.

```
WARNING: tempfile is deprecated; consider using mktemp instead.
```

**Comment by jeremyVignelles** [comment]
The culprit seems to be here : https://github.com/inetum-orleans/docker-devbox-ddb/blob/27073419e01c9c5f3ca8b229a7dac2e7cdd7dda8/ddb/feature/shell/integrations.py#LL150C25-L150C25
Didn't have time to replace it yet, leaving it for another day.
