### ISSUE TITLE
Force docker-compose.yml file path when a conflicting file exists

### ISSUE THREAD

**Issue by jeremyVignelles** [inetum-orleans/docker-devbox-ddb#222]
I have a folder in which I want to setup a ddb environment for a project I clone under it.
That cloned project have a docker-compoe.yml file, which the `docker compose run` uses by default, when I run `$(ddb run npm)`.

This is due to this part of the code :
https://github.com/inetum-orleans/docker-devbox-ddb/blob/ffb8f1916c559f3392bed8164a734f333fc54117/ddb/feature/docker/binaries.py#L64

Either we should provide a way to override this behavior manually, or we need to detect that conflicting docker-devbox.yml file, and force the `-f` option in that case. Another option would be just putting `-f` every time on the commands, to avoid such conflict.

What do you think ?

**Comment by Toilal** [comment]
`export DDB_RUN_OPTS="-f ${DDB_PROJECT_HOME}"` should work as a workaround for now, but I'll appreciate a pull request adding the -f flag on every `ddb run` command.
