### ISSUE TITLE
The version in docker-compose.yaml generated is obsolete

### ISSUE THREAD

**Issue by Vincere1st** [inetum-orleans/docker-devbox-ddb#229]
Do a new installation of docker devbox
and go to the folder ~/.docker-devbox/traefik and run docker compose ps a warning appear:

![image](https://github.com/inetum-orleans/docker-devbox/assets/7150501/3ea9631e-539c-4a6e-9ccb-ebb01570f314)

same on portainer.

Perhaps remove the version tag of the generated file if there is no replacement.

**Comment by jeremyVignelles** [comment]
The "version" key seems to have been removed when moving from docker-compose to docker compose.
Now that we have `docker compose` all the way, we could drop support for docker-compose and remove that version key.

source : https://docs.docker.com/compose/intro/history/

**Comment by jeremyVignelles** [comment]
Fixed in https://github.com/inetum-orleans/docker-devbox-ddb/commit/7bc7719a1ade9be7fe1d9684ea123a430d6192f9
will be released as ddb 3.0
